kind: pipeline
name: live-stream-user-service

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: jeremyaherzog/live-stream-user-service
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
  - name: replace-text
    image: jeremyaherzog/drone-text-replacement
    settings:
      filename: deployment.yaml
      version: ${DRONE_COMMIT_SHA}
  - name: deploy
    image: vallard/drone-kube
    template: deployment.yaml

trigger:
  branch:
  - master
  event:
  - push
