kind: pipeline
name: live-stream-user-service

steps:
  - name: build
    image: plugins/docker
    environment:
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: herzo175/live-stream-user-service
      tags:
        - latest
        - $DRONE_REPO/$DRONE_COMMIT
